# Generated by Django 4.0.5 on 2022-06-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='odered',
            new_name='ordered',
        ),
    ]
