# Generated by Django 4.0.5 on 2022-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0002_rename_odered_panier_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.FloatField(null=True),
        ),
    ]
