# Generated by Django 4.0.5 on 2022-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0003_alter_commande_prix_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_total',
        ),
    ]
