# Generated by Django 4.0.5 on 2022-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0004_remove_commande_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.ManyToManyField(related_name='order', to='ecommerceapk.panier'),
        ),
    ]
