# Generated by Django 4.0.5 on 2022-06-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0005_alter_commande_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
