# Generated by Django 4.0.5 on 2022-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0006_commande_prix_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_total',
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
