# Generated by Django 4.0.5 on 2022-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0007_remove_commande_prix_total_alter_panier_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
