# Generated by Django 4.0.5 on 2022-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0008_alter_commande_date_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
