# Generated by Django 4.0.5 on 2022-06-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0009_commande_prix_total_alter_panier_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
