# Generated by Django 4.0.5 on 2022-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapk', '0010_alter_panier_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix_total',
        ),
    ]
